config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users 

  get 'profile', to: 'users#profile'
  get '/users/:id', to: 'users#show'
  root 'welcome#index'

  #LOGIN
  get '/users-form-signup' => 'users#get_form_sign_up'
  get '/users-form-signin' => 'users#get_form_sign_in'

  #DONATE
  get 'donor/donate', to: 'donations#new'
  post 'donor/donate', to: 'donations#create'

  get 'donor/donate/products', to: 'products#new'
  post 'donor/donate/products', to: 'products#create'

  #DONATION LIST
  get '/donations', to: 'donations#index'

  #FIND DONATION
  get '/donations/:id', to: 'donations#show'

  #BANKS LIST
  get '/banks', to: 'users#banks'

  #RANKING LIST
  get '/donors', to: 'users#donors'

  #BANK REQUEST
  post '/donations/:id', to: 'donations#update'

  put '/donations/:donation_id', to: 'donations#update', as: 'donors_put'

  #DESTROY REQUEST
  delete '/donations/:id', to: 'donations#destroy'
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  belongs_to :bank, class_name: "User", foreign_key: "bank_id"
  belongs_to :donor, class_name: "User", foreign_key: "donor_id"
  has_many :products, :dependent => :delete_all

  validates :description, presence: true 
  validates :description, length: {maximum: 30} 

  def user
    User.where("bank_id = ? OR donor_id = ?", self.id, self.id)
  end

  def self.last_created_donations(n)
    Donation.order(id = 1).first(n) 
  end

  def self.get_winner_donation
    Donation.first
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  
  def index
    # if the id params is present
    if params[:id]
      # get all records with id less than 'our last id'
      # and limit the results to 5
      @donations = Donation.where('id < ?', params[:id]).limit(6)
    else
      @donations = Donation.limit(9)
    end
    respond_to do |format|
      format.html
      format.js { }
    end 
  end

  def new
    @user = current_user
    @donation = @user.donor_donations.new
  end
  def create
    @user = current_user
    @donation = @user.donor_donations.new(donation_params)

    if @donation.save
      flash[:notice] = "Muy bien! Ahora debes agregar alimentos."
      redirect_to action: 'new', controller: 'products' 
    else
      flash[:alert] = "You need to fill the camps"
      render 'new'
    end

  end
  def show
    @donation = Donation.find(params[:id]) || render_404(params) 
    @products = @donation.products
    @donation_bank_id = @donation.bank_id
    @donation_donor_id = @donation.donor_id
  end

  def update

    if params[:donation_id]
      @donation = Donation.find(params[:donation_id]) || render_404(params) 

      @donation.update_attributes({ :bank_id => nil })

      redirect_to donors_put_path(@donation), notice: 'Solicitud eliminada'

    else
      @donation = Donation.find(params[:id]) || render_404(params) 
      @user = current_user.id
      @nil = nil

      @donation.update_attributes({ :bank_id => @user })

        respond_to do |format|
          format.js { }
          format.html { redirect_to root_path, notice: 'no' }
      end      
    end
  end

  def destroy
    @donation = Donation.find(params[:id]) || render_404(params) 
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Donación eliminada exitosamente' }
    end   
  end

  private
  def donation_params
    params.require(:donation).permit(:date, :description)
  end
  def product_params
    params.require(:product).permit(:category, :name, :amount, :date)
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<div class='col-md-4 col-sm-6 col-xs-12'>
  <div class='donor-box' data-id="<%= donation.id %>">
    <% if donation.description.present? %>
    <div class='row'>
      <div class='col-md-9 col-sm-9 col-xs-9'>
        <h6>Donante</h6>
        <h3><%= "#{donation.donor.name}" %></h3>
        <h5>Estado<span>Disponible</span></h5>
      </div>
      <div class='col-md-3 col-sm-3 col-xs-3'>
        <div class='donor-logo-container'><span class="glyphicon glyphicon-user"></span></div>
      </div>
    </div>
      <div class='bottom'>
        <!--<div class="button-wrap"><button data-dialog="somedialog" class="trigger">Open Dialog</button></div>-->
        <a href='/donations/<%= donation.id %>' class='btn-do'>Ver canasta</a>
      </div>
    <% end %>
  </div>
</div>

app/views/donations/_form.html.erb
<% if @donation.errors.any? %>
<ul>
  <% @donation.errors.full_messages.each do |donation| %>
  <li><%= donation %></li>
  <% end %>
</ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form class="new_donation" id="new_donation" action="/donor/donate" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="6bHg9h10h5Vigv7hquw4fDgojW6ybzjhtcmivoW1sJP/gRb4FEBZN+jx5cmGaK0HC0olegFZhgVO775OMhx4dw==">
        <h2 class='title-form'>Rellena los datos de la donación</h2>
        <p>* Danos una descripción breve sobre los objetivos de la donación y otros factors que condicionen superficialmente su propósito.</p>
        <label for="donation_description">Descripción</label>
        <textarea type="text" placeholder="Agrega una descripción para titular la nueva donación" name="donation[description]" id="donation_description"></textarea>
        <br>
        <label for="donation_date">Fecha de expiración</label>
        <input type="date" name="donation[date]" id="donation_date">
        <br>
      <input class='btn-do' type="submit" name="commit" value="Enviar">
    </form>
  </div>
</div>

app/views/donations/index.html.erb
<div class='head-image'>
  <div class='overlay'></div>
    <h1 class='single-page'>Donaciones</h1>
    <h2 class='single-page'>Aquí encontrarás todas las donaciones disponibles.</h2>
  <img src='http://www.ewao.com/wp-content/uploads/2016/02/health-organic-food-2716-x-1810-agracultura.org_.jpg'>
</div>
<div class='container'>
<div class='row margin-for-head-image'>
  <div id='donations'>
    <%= render @donations %>
  </div>
</div>

<hr class='separator minor'></hr>
  <div class="load-more-container">

    <%= image_tag "ajax-loader.gif", style: "display:none;", class: "loading-gif" %>
    <%= link_to "Load More", donations_path, class: "btn-do load-more margin-helper" %>
  </div>

</div>

app/views/donations/index.js.erb
// append the users partial to our div with class of container
$('#donations').append('<%= escape_javascript(render(:partial => @donations)) %>')

app/views/donations/new.html.erb
<div class='container'>
  <div class='margin-for-nav'>
    <%= render 'form' %>
  </div>
</div>

app/views/donations/show.html.erb
<div class='back-image'>
<div class='overlay'></div>
<div class='container'>
  <div class='margin-for-nav'>
    <div class="row">
      <div id='donation-info' class='col-md-4'>
        <h5><%= @donation.donor.name %></h5>
        <h1 class='donation-title'><%= @donation.description %></h1>
        <h3><%= @donation.date %></h3>
        <% if @donation_bank_id %>
          <span class='state-donation requested'>Donación solicitada</span>
        <% else %>
          <span class='state-donation available'>Donación disponible</span>
        <% end %>
      </div>
      <div class='col-md-8'>
        <% if @products.any? %>
        <form id="new_request" action="/donations/<%= @donation.id %>" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden">
          <h2>Lista de alimentos</h2>
          <ol>
          <% @products.each do |product| %>
            <li><%= product.name %> - (<%= product.amount %>)</li>
          <% end %>
          </ol>
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.is_a_donor? %>
            <p class="margin-notification">
              <% if current_user.id == @donation_donor_id %>
              * Como autor tienes la opción de eliminar esta donación.
              <% else %>              
              * Necesitas estar registrado como banco para solicitar esta u otra donación.
              <% end %>
            </p>
            <% if current_user.id == @donation_donor_id %>
            <a class='btn-do' rel="nofollow" data-method="delete" href="/donations/<%= @donation.id %>">Eliminar donación</a>
            <% else %>
            <a class='btn-do' href="/donor/donate">Hacer una donación</a>
            <% end %>
          <% else %>
            <% if @donation_bank_id %>
              <p class="margin-notification"><% if current_user.id == @donation_bank_id %>
                * Has solicitado esta donación. Tienes la opción de eliminar tu solicitud.
                  <% else %>    
                * Esta donación ya está solicitada por <span class='bank'><%= @donation.bank.name %></span>
                  <% end %>
              </p>
              <a href="/donations" class='btn-do'>Ver más donaciones</a>
              <% if current_user.id == @donation_bank_id %>

              <%= link_to "Eliminar solicitud", donors_put_path(@donation), :method=> :put, :class => "btn-do"%>
       
              <% else %>          
              <% end %>
            <% else %>
              <p class="margin-notification">Esta donación está disponible gracias a <span class='donor'><%= @donation.donor.name %></span></p>
              <input type="hidden" name="donations[bank_id]" value="<%= current_user.id %>" id="_donations_bank_id"></input>
              <input class='btn-do donation-request' type="submit" name="commit" value="Solicitar donación">
            <% end %>
          </form>
          <% end %>
        <% else %>
          <div class='link-group'>
            <a data-toggle="modal" data-target="#sign-modal" href="#" class='signup btn-do group'>Regístrate</a>
            <a data-toggle="modal" data-target="#sign-modal" href="#" class='signin btn-do group'>Inicia sesión</a>
            
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/donations/update.js.erb
var requested = "<a class='btn-do btn-disabled' href='/donations'>Donación Solicitada...</a>";
var eliminate = "<div class='row'><div class='col-md-12'><a class='btn-do' rel='nofollow' data-method='put' href='/donations/120'>Eliminar solicitud</a></div></div>";
var message = "<p class='margin-notification'>* Has solicitado esta donación!</p>";
var state = "<span class='state-donation requested'>Donación solicitada</span>";

$('.btn-do').remove();
$('.state-donation').remove();

$('.margin-notification').remove();
$('#new_request').append(message);

$('#new_request').append(requested);
$('#new_request').append(eliminate);
$('#donation-info').append(state);